### ISSUE TITLE
Build framework as a 3rd-party lib

### ISSUE THREAD

**Issue by ngvincent** [ma1co/PMCADemo#3]
Pull the framework/ folder out, build it as a third party lib/jar

When other people write apps for PMCA, they'll just have to include that lib/jar in the build path, without having to copy the framework code.

(Optionally put that lib/jar in maven repository, so that it can be added as a maven/gradle/... dependency)

I can assist on this - Let me know if you want me to help

**Comment by ma1co** [comment]
I'm planning to do this eventually. For the time being, i'm just investigating in the APIs and it's IMHO easier to have everything in one single project. Especially because I don't know yet in which form we will release this framework, whether we have to add a custom intermediate code layer for example.

The framework directory contains just some stubs for the Sony APIs. They are more or less auto-generated from the unpacked firmware.

So I would propose to wait a bit before we really release the framework.

**Comment by ngvincent** [comment]
Ok.... 

Do you need help in any specific item? Are you looking at the firmwares for a specific camera, or for all available cameras?

**Comment by ma1co** [comment]
Mainly testing atm... I only have an a6000, it would be great if you could test everything on your camera, too.

The stubs come mainly from the nex6 which is one of the oldest cameras with android apps enabled (just after the nex5r). The features present in this camera should (hopefully) work on most newer cameras, too.

**Comment by lh8511** [comment]
I had the Nex-6 (now sold) and tested successfully all functions of PMCADemo until v0.6... 
I tried to compile some useful code from other camera apps but the whole implementation was too changeling for my code expertise, LOL
I am now waiting to get the A7 or A7II and hopefully all should work too...

**Comment by lh8511** [comment]
Any development on the framework (library) side?

**Comment by ngvincent** [comment]
Sorry, been bit busy at work, didn't have much time to work on this

If you look at my fork, I've added code that makes it easier to browse and
dump the filesystem of your current camera (instead of just working on the
decompiled nex6). If you have an A7, share the jars?(I'll share mine later
tonight)

Think I have time to look at it in a few weeks when things quiet down
On Oct 20, 2015 6:13 AM, "lh8511" notifications@github.com wrote:

Any development on the framework (library) side?

**Comment by lh8511** [comment]
Ok thanks,
Will check

**Comment by lh8511** [comment]
@ngvincent 
I still do not decided which version of A7 to get! Will be probably A7ii or simple A7.
Anyway I got a dump for A7s in my disk. What Jars do you want?
-What camera do you have?

**Comment by ma1co** [comment]
Hi everyone, sorry for my late answer, I've been very busy in the last months and couldn't work on this.

In the last few days, I reverse engineered the USB communication between camera and browser plugin. I mean, nobdy wants to use IE :) I just pushed my results to the other repo.

Concerning the framework, my goal is to develop an abstraction layer with a nice scripting interface, so people can write their own scripts (probably JavaScript, since interpreters are easy to integrate) and have them interpreted on camera. That would lower the entry barrier for many people. What do you think?

**Comment by lh8511** [comment]
Welcome ma1co. 
A scripting interface would be very cool.

**Comment by tommiehansen** [comment]
@ma1co as someone that works as a designer and a front end designer that would be pretty awesome since javascript is one of the few languages i actually understand :+1:

**Comment by gped73** [comment]
hi @ma1co , I have tested the python code with a7s and it work great, also the apk install well !
Now i'd like to write an app to force 4k internal recording, I am trying to build an APK from your PMCADemo project, but i am not able. I don't know very well android programming. Please what i have to do to build the APK ?
At the moment i found Android Studio, with Android 2.3 Platform SDK, but something go wrong.
Please help me, thank's a lot

**Comment by ma1co** [comment]
I've pulled out the stubs and I'm currently writing a new abstraction framework around them: [OpenMemories-Framework](https://github.com/ma1co/OpenMemories-Framework).
