### ISSUE TITLE
New name for PMCA open-source framework?

### ISSUE THREAD

**Issue by ngvincent** [ma1co/PMCADemo#4]
PMCA stands for PlayMemories Camera App

Sony might not like this project having the same name as the official app (confusion for consumers), and could send a C&D (cease and desist letter) to github

Could avoid this issue entirely by getting a new name (description could still be "xxx-name is an opensource framework that replicates Sony's PMCA, achieved via reverse-engineering Sony's PMCA framework)

**Comment by ma1co** [comment]
Well, this really started as a reverse engineering project (and still is). So I didn't bother and just called it PMCA-RE. But especially for the "framework" / stubs we want to publish, this is a valid concern.

Do you have any creative ideas for a name? I can only propose something with "ScalarA", this seems to be the name internally used by Sony for the whole android stuff and isn't trademarked i guess...

**Comment by tommiehansen** [comment]
I find that it is very hard to remember the wording PMCA-RE. I actually did try to invent a new name but most came out sounding lame in some way or the other.

What i did was try to combine these words:
Sony (Trademark?)
Apps
App
Camera
Playmemories (Trademark?)
Reverse
Engineer
Interface
UI
Custom
More
Enhanced
New

It was really challening to come up with something though. The problem is that the words Sony and Playmemories is a huge part of what it is yet maybe cannot be used. Also the word "Playmemories" doesn't easily roll of the tongue. All names should make the project easy to find (easy to google, easy to find more information about etc -- something that the current project name sort of lack since it's also harder to spell).

Some of these bad suggestions include:
More Memories (Sony MM)
Reverse Memories (Sony RM)
Custom Memories (CM -- worser 'findability' since CM = Cyanogenmod for Android)
REM (Reverse Engineered Memories)
MCA (More Camera Apps)

etc etc.. :)

**Comment by aggregate** [comment]
I like REM, except you're not really RE-ing the memories. How about something like:
MADE (Memory Application Development Environment)
UMADE (User/Unofficial/Unauthorized/Unsupported MADE)
REMADE (Reverse-Engineered MADE)
COMADE (Camera/Community Open MADE)

You can also stick an S on the end of any of the above to add "for Sony"

**Comment by sonovice** [comment]
Just my 2 cents: OpenMemories

Merry Christmas in advance, folks!

2015-12-22 14:35 GMT+01:00 aggregate notifications@github.com:

> I like REM, except you're not really RE-ing the memories. How about
> something like:
> MADE (Memory Application Development Environment)
> UMADE (User/Unofficial/Unauthorized/Unsupported MADE)
> REMADE (Reverse-Engineered MADE)
> COMADE (Camera/Community Open MADE)
> 
> You can also stick an S on the end of any of the above to add "for Sony"
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ma1co/PMCADemo/issues/4#issuecomment-166620231.

## 

Simon Waloschek
Paulinenstr. 58
32756 Detmold

+49 151 5111 82 89

**Comment by tommiehansen** [comment]
@sonovice Yes, forgot that one -- it's a good and simple one. :)

**Comment by aggregate** [comment]
I like OpenMemories.
Even better in the dual meaning of open as an action performed to play a file. ;-)

**Comment by areichow** [comment]
I also like OpenMemories. The Open distinguishes it from Sony's proprietary
and off-limits stack, while Memories links it with Sony's branding. A name
that reflected the fact that it's the first open platform for camera
applications would be good, and I think that is somewhat achieved with
OpenMemories. :-)

**Comment by ma1co** [comment]
I've created a new repo for the framework (under development): [OpenMemories-Framework](https://github.com/ma1co/OpenMemories-Framework). I might decide to rename the other repos as well. Thx to @sonovice for the idea for the name!
